### ISSUE TITLE
The example does not produce a valid svg file

### ISSUE THREAD

**Issue by WestleyR** [reddec/svg#1]
Hi, very nice code, however it does not produce a valid svg file with the given example. I was able to tweak the code a little and get it sorta working (seems to be missing some svg header components). I can submit a PR but this project does not seem to be maintained anymore :(

**Comment by reddec** [comment]
I will very much appreciate your help and will be happy to assist you with PR.

**Comment by WestleyR** [comment]
Okay, I will make a pull request :+1: Also, on my own fork I'v changed the api for my application needs. I'll be happy to show you the differences, but not sure you are interested in those changes...
